In [2]:
import numpy as np


In [13]:
t=(1,2,3)
a=np.array(t,dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [56]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.linspace(0,45,7)

array([ 0. ,  7.5, 15. , 22.5, 30. , 37.5, 45. ])

In [252]:
np.random.randn?

In [253]:
a=np.random.randn(2,2,3)
a

array([[[-1.07610503, -0.18234311,  0.45666172],
        [-0.9809555 , -1.42101796, -1.92266756]],

       [[ 0.7109955 ,  0.224153  ,  1.20710353],
        [ 1.39195424,  0.35268262,  0.60570634]]])

In [247]:
f=np.

In [255]:
np.random.random?

In [254]:
np.random.random((3,2,3))

array([[[0.67404544, 0.57888994, 0.9132107 ],
        [0.38411424, 0.02461986, 0.39025425]],

       [[0.00978629, 0.97243366, 0.43283353],
        [0.08269543, 0.01849368, 0.92831814]],

       [[0.83788099, 0.53483538, 0.68952864],
        [0.55536535, 0.92449986, 0.90073255]]])

randn是采用标准正态分布，且只需要在括号内完成shape定义就行；random是在[0.0 , 1,0)  内随机取数，类型为float，且定义shape时要在加一个括号( )

In [260]:
f=np.array([  [1,2],[2,3] ])
f

array([[1, 2],
       [2, 3]])

In [261]:
f.cumsum(axis=1) # 行叠加

array([[1, 3],
       [2, 5]])

In [262]:
f.cumsum(axis=0) # 列叠加

array([[1, 2],
       [3, 5]])

axis=1表示一行；axis=0表示一列

In [50]:
c=np.add(a,b)
c

array([[ 0.20030284,  0.81631448, -1.04883261],
       [-0.16938894,  2.59197869,  1.45708615],
       [-1.38949605, -0.01174541,  0.94266909]])

In [52]:
c.sum()

3.3888882377055882

In [54]:
c.min(axis=0)

array([-1.38949605, -0.01174541, -1.04883261])

In [58]:
a.dot(b)

array([[-0.79969716,  0.81631448, -1.04883261],
       [-0.16938894,  1.59197869,  1.45708615],
       [-1.38949605, -0.01174541, -0.05733091]])

In [62]:
np.arange(0,24,4)

array([ 0,  4,  8, 12, 16, 20])

In [65]:
def f(a,b):
    return 5*a+b
b=np.fromfunction(f,(2,2),dtype=int)
b

array([[0, 1],
       [5, 6]])

In [66]:
np.fromfunction?

In [67]:
b[1]

array([5, 6])

In [68]:
b[:,1]

array([1, 6])

In [70]:
b[0]=0
b

array([[0, 0],
       [5, 6]])

In [71]:
b[:,1]=2
b

array([[0, 2],
       [5, 2]])

In [72]:
work_day=np.array(['Mon','Tue','Wed','Thu','Fri'])

In [86]:
work_time=np.round(np.random.randn(5,5)+8.0,2)  # np.round(obj, num)表示将目标保留num位小数
work_time            

array([[ 8.14,  7.58,  7.14,  7.05,  7.08],
       [ 7.91,  6.61,  8.05,  6.14,  5.82],
       [ 8.29,  7.12,  7.7 ,  7.68,  7.58],
       [ 5.55,  8.64,  7.77,  7.7 ,  9.02],
       [ 7.05,  7.41,  7.3 ,  6.77, 10.26]])

In [87]:
work_time[work_day=='Mon'] # work_day=='Mon'作为条件，会返回一个bool的list，然后将表示为True的对应行挑选出来

array([[8.14, 7.58, 7.14, 7.05, 7.08]])

In [93]:
a=np.array([[1,2,3],[4,5,6]] ,dtype='float')
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [91]:
a.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [94]:
b=np.array([ [ [1,2,3,4],[3,4,5,6]     ]    ], dtype=float)
b

array([[[1., 2., 3., 4.],
        [3., 4., 5., 6.]]])

In [95]:
b.shape


(1, 2, 4)

In [97]:
b.T.shape

(4, 2, 1)

In [98]:
b

array([[[1., 2., 3., 4.],
        [3., 4., 5., 6.]]])

In [141]:
a=np.array([[2,10,3]])
a

array([[ 2, 10,  3]])

In [176]:
c=np.array([[1.,2.,4.],[3.,4.,9.]])
c

array([[1., 2., 4.],
       [3., 4., 9.]])

In [177]:
np.dot(c.T,c)

array([[10., 14., 31.],
       [14., 20., 44.],
       [31., 44., 97.]])

In [202]:
np.linalg.inv( np.array([ [10,14,18],
       [14,20,26],
       [18,26,39] ]) )


array([[ 5.2, -3.9,  0.2],
       [-3.9,  3.3, -0.4],
       [ 0.2, -0.4,  0.2]])

In [203]:
10*20*34+14*26*18+14*26*18-18*20*18-14*14*34-26*26*10

0

In [207]:
from numpy.linalg import *
a=np.array([  [1,2],[3,4]  ])
ainv=inv(a)
np.allclose(np.dot(a,ainv),np.eye(2))
np.allclose(np.dot(ainv,a),np.eye(2))

True

比较两个变量的差值在10e-8以内,即标记为正，返回是一个bool（判断值）

In [208]:
eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

求特征向量

In [210]:
np.trace(a)

5

求矩阵的迹


In [213]:
a=np.arange(50).reshape(5,5,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [215]:
a.transpose(0,2,1)

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]],

       [[20, 22, 24, 26, 28],
        [21, 23, 25, 27, 29]],

       [[30, 32, 34, 36, 38],
        [31, 33, 35, 37, 39]],

       [[40, 42, 44, 46, 48],
        [41, 43, 45, 47, 49]]])

In [272]:
a=np.array([   [1,2],[3,4]  ,[4,5]     ])
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [273]:
a.swapaxes(1,0) # 对调坐标轴


array([[1, 3, 4],
       [2, 4, 5]])

In [274]:
a.swapaxes(0,1)

array([[1, 3, 4],
       [2, 4, 5]])

In [244]:
b=np.array([ [ 0,  2,  8,  6,  8, 1,  3,  5,  7,  9 ]])
b[0][6]


3

In [246]:
np.bincount(b[0])

array([1, 1, 1, 1, 0, 1, 1, 1, 2, 1])